management:
  endpoints:
    web:
      exposure:
        include: info, metrics, prometheus

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect